version: '3.8'

services:
  db:
    image: mysql:8
    container_name: chatbot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chatbot_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: chatbot_backend
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

volumes:
  db_data: